# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "HOTEL" ("ID" SERIAL NOT NULL PRIMARY KEY,"NAME" VARCHAR(254) DEFAULT '' NOT NULL,"phone" VARCHAR(254) DEFAULT '' NOT NULL,"FAX" VARCHAR(254) DEFAULT '' NOT NULL,"EMAIL" VARCHAR(254) DEFAULT '' NOT NULL,"WEB_SITE" VARCHAR(254) DEFAULT '' NOT NULL,"RATE" VARCHAR(254) DEFAULT '' NOT NULL,"IMAGE" VARCHAR(254) DEFAULT '' NOT NULL,"STAR" INTEGER NOT NULL,"DIST_CENTER" VARCHAR(254) DEFAULT '' NOT NULL,"HOTEL_TYPE" INTEGER DEFAULT 0 NOT NULL,"ENTRANCE" VARCHAR(254) DEFAULT '12:00' NOT NULL,"EXIT" VARCHAR(254) DEFAULT '12:00' NOT NULL,"REGION_ID" INTEGER NOT NULL,"CITY_ID" INTEGER NOT NULL,"ADDRESS" VARCHAR(254) DEFAULT '' NOT NULL,"LATITUDE" DOUBLE PRECISION NOT NULL,"LONGITUDE" DOUBLE PRECISION NOT NULL);
create table "HOTEL_ADMIN" ("ID" SERIAL NOT NULL PRIMARY KEY,"HOTEL_ID" INTEGER NOT NULL,"FIRST_NAME" VARCHAR(254) NOT NULL,"LAST_NAME" VARCHAR(254) NOT NULL,"LOGIN" VARCHAR(254) NOT NULL,"PASSWORD" VARCHAR(254) NOT NULL,"EMAIL" VARCHAR(254) NOT NULL,"PHONE" VARCHAR(254) NOT NULL);
create table "HOTEL_TYPE" ("ID" SERIAL NOT NULL PRIMARY KEY,"NAME" VARCHAR(254) DEFAULT '' NOT NULL);
create table "REVIEW" ("ID" SERIAL NOT NULL PRIMARY KEY,"HOTEL_ID" INTEGER NOT NULL,"USER_ID" INTEGER NOT NULL,"LAST_NAME" VARCHAR(254) NOT NULL,"IS_ACTIVE" BOOLEAN NOT NULL,"CREATED_AT" TIMESTAMP NOT NULL);
create table "ROOM" ("ID" SERIAL NOT NULL PRIMARY KEY,"HOTEL_ID" INTEGER NOT NULL,"ROOM_TYPE" INTEGER NOT NULL,"COUNT" INTEGER NOT NULL,"PRICE" DOUBLE PRECISION NOT NULL,"DISCOUNT" DOUBLE PRECISION DEFAULT 0.0 NOT NULL,"WIFI" BOOLEAN DEFAULT false NOT NULL,"BREAKFAST" VARCHAR(254) DEFAULT '' NOT NULL,"PARKING" BOOLEAN DEFAULT false NOT NULL,"FITNESS" BOOLEAN DEFAULT false NOT NULL,"POOL" BOOLEAN DEFAULT false NOT NULL,"TRANSPORT" VARCHAR(254) DEFAULT '' NOT NULL,"BAR_REST" VARCHAR(254) DEFAULT '' NOT NULL,"BATHROOM" VARCHAR(254) DEFAULT '' NOT NULL);
create table "ROOM_TYPE" ("ID" SERIAL NOT NULL PRIMARY KEY,"NAME" VARCHAR(254) NOT NULL);
create table "USER" ("ID" SERIAL NOT NULL PRIMARY KEY,"USERNAME" VARCHAR(254) NOT NULL,"EMAIL" VARCHAR(254) NOT NULL,"AGE" INTEGER NOT NULL);
alter table "HOTEL" add constraint "HOTEL_FK_HOTEL_TYPE_ID" foreign key("HOTEL_TYPE") references "HOTEL_TYPE"("ID") on update NO ACTION on delete NO ACTION;
alter table "HOTEL_ADMIN" add constraint "HOTEL_ADMIN_FK_HOTEL_ID" foreign key("HOTEL_ID") references "HOTEL"("ID") on update NO ACTION on delete NO ACTION;
alter table "REVIEW" add constraint "REVIEW_FK_HOTEL_ID" foreign key("HOTEL_ID") references "HOTEL"("ID") on update NO ACTION on delete NO ACTION;
alter table "REVIEW" add constraint "REVIEW_FK_USER_ID" foreign key("USER_ID") references "USER"("ID") on update NO ACTION on delete NO ACTION;
alter table "ROOM" add constraint "ROOM_FK_HOTEL_ID" foreign key("HOTEL_ID") references "HOTEL"("ID") on update NO ACTION on delete NO ACTION;
alter table "ROOM" add constraint "ROOM_FK_ROOM_TYPE" foreign key("ROOM_TYPE") references "ROOM_TYPE"("ID") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "ROOM" drop constraint "ROOM_FK_HOTEL_ID";
alter table "ROOM" drop constraint "ROOM_FK_ROOM_TYPE";
alter table "REVIEW" drop constraint "REVIEW_FK_HOTEL_ID";
alter table "REVIEW" drop constraint "REVIEW_FK_USER_ID";
alter table "HOTEL_ADMIN" drop constraint "HOTEL_ADMIN_FK_HOTEL_ID";
alter table "HOTEL" drop constraint "HOTEL_FK_HOTEL_TYPE_ID";
drop table "USER";
drop table "ROOM_TYPE";
drop table "ROOM";
drop table "REVIEW";
drop table "HOTEL_TYPE";
drop table "HOTEL_ADMIN";
drop table "HOTEL";

